# Generated by Django 4.0.1 on 2022-01-31 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospital')),
                ('Citizenship_Number', models.CharField(default='', max_length=50)),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 31, 15, 56, 55, 743857, tzinfo=utc))),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospital')),
                ('Phone_Number', models.CharField(default='', max_length=14)),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 31, 15, 56, 55, 742832, tzinfo=utc))),
                ('Address', models.CharField(max_length=500)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalStatus',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospitalStatus')),
                ('Vaccine_Code', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 31, 15, 56, 55, 743857, tzinfo=utc))),
                ('Total_Assigned_Vaccine', models.IntegerField(default=0)),
                ('Used_Vaccine', models.IntegerField(default=0)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='username')),
                ('Citizenship_Number', models.CharField(default='', max_length=50)),
                ('DOB', models.DateField()),
                ('Date', models.DateField(default=datetime.datetime(2022, 1, 31, 15, 56, 55, 741856, tzinfo=utc))),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
