# Generated by Django 4.0.1 on 2022-02-02 06:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospital')),
                ('Citizenship_Number', models.CharField(default='', max_length=50)),
                ('Date', models.DateField(default=datetime.datetime(2022, 2, 2, 6, 13, 39, 339333, tzinfo=utc))),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 58, 39, 346876))),
                ('Chat_Body', models.TextField()),
                ('Remarks', models.CharField(max_length=100)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospital')),
                ('Phone_Number', models.CharField(default='', max_length=14)),
                ('Date', models.DateField(default=datetime.datetime(2022, 2, 2, 6, 13, 39, 339333, tzinfo=utc))),
                ('Address', models.CharField(max_length=500)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalStatus',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='hospitalStatus')),
                ('Vaccine_Code', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.datetime(2022, 2, 2, 6, 13, 39, 346876, tzinfo=utc))),
                ('Total_Assigned_Vaccine', models.IntegerField(default=0)),
                ('Used_Vaccine', models.IntegerField(default=0)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='username')),
                ('Citizenship_Number', models.CharField(default='', max_length=50)),
                ('DOB', models.DateField()),
                ('Date', models.DateField(default=datetime.datetime(2022, 2, 2, 6, 13, 39, 339333, tzinfo=utc))),
                ('Health_Stat', models.BooleanField(default=False)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userStatus',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='userStatus')),
                ('First_Dose_Date', models.CharField(default='', max_length=100)),
                ('Second_Dose_Date', models.CharField(default='', max_length=100)),
                ('New_Vaccine_Request', models.BooleanField(default=False)),
                ('New_Vaccine_Location', models.CharField(default='', max_length=500)),
                ('Current_PCR', models.BooleanField(default=False)),
                ('Schedule_Stat', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 58, 39, 339333))),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_Content', models.TextField(default='')),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 58, 39, 346876))),
                ('Seen_Status', models.BooleanField(default=False)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_body', to='authentication.chat')),
            ],
        ),
    ]
