# Generated by Django 4.0.1 on 2022-01-31 16:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userStatus',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='userStatus')),
                ('First_Dose_Date', models.DateField(default=None)),
                ('Second_Dose_Date', models.DateField(default=None)),
                ('New_Vaccine_Request', models.BooleanField(default=False)),
                ('Current_PCR', models.BooleanField(default=False)),
                ('Date', models.DateField(verbose_name=datetime.datetime(2022, 1, 31, 16, 23, 23, 989222, tzinfo=utc))),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 16, 23, 23, 990251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 16, 23, 23, 990251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 16, 23, 23, 991216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 16, 23, 23, 989222, tzinfo=utc)),
        ),
    ]
