# Generated by Django 4.0.1 on 2022-02-02 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_chatbody_chat_alter_adminprofile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 6, 30, 38, 64497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 6, 30, 38, 64497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 6, 30, 38, 64497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 6, 30, 38, 64497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 15, 38, 64497)),
        ),
    ]
