# Generated by Django 4.0.1 on 2022-01-30 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_hospitalprofile_alter_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Profile_Picture',
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 16, 22, 33, 799735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 16, 22, 33, 799735, tzinfo=utc)),
        ),
    ]
