# Generated by Django 4.0.1 on 2022-01-31 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_adminprofile_date_alter_hospitalprofile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='New_Vaccine_Location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 17, 25, 11, 203536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 17, 25, 11, 203536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 17, 25, 11, 204536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 17, 25, 11, 201537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 17, 25, 11, 201537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='First_Dose_Date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Second_Dose_Date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
