# Generated by Django 4.0.1 on 2022-01-30 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_address_remove_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Citizenship_Number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 16, 25, 40, 391142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 16, 25, 40, 391142, tzinfo=utc)),
        ),
    ]
