# Generated by Django 4.0.1 on 2022-02-01 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userstatus_new_vaccine_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='New_Vaccine_Request_Date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 7, 29, 46, 729351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 7, 29, 46, 729351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 7, 29, 46, 729351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 7, 29, 46, 727331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 7, 29, 46, 728350, tzinfo=utc)),
        ),
    ]
