# Generated by Django 4.0.1 on 2022-02-01 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_adminprofile_date_alter_hospitalprofile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='New_Vaccine_Request_Date',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 8, 31, 0, 612906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 8, 31, 0, 611906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 8, 31, 0, 612906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 8, 31, 0, 610906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 8, 31, 0, 610906, tzinfo=utc)),
        ),
    ]
