# Generated by Django 4.0.1 on 2022-02-01 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_scheduled_stat_userstatus_schedule_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 6, 27, 254200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 6, 27, 253200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 6, 27, 254200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 6, 27, 251200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 16, 51, 27, 252213)),
        ),
    ]
