# Generated by Django 4.0.1 on 2022-02-01 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_adminprofile_date_alter_hospitalprofile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 8, 19, 18067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 8, 19, 17068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstatus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 8, 19, 18067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 8, 19, 15069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 16, 53, 19, 16070)),
        ),
    ]
