# Generated by Django 4.0.1 on 2022-02-02 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 13, 9, 423233))),
                ('Chat_Body', models.TextField()),
                ('Remarks', models.CharField(max_length=100)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_Content', models.TextField(default='')),
                ('Date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 13, 9, 423233))),
                ('Seen_Status', models.BooleanField(default=False)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_body', to='messenger.chat')),
            ],
        ),
    ]
