# Generated by Django 4.0.1 on 2022-02-02 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_remove_chat_chat_body_alter_chat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbody',
            name='Sender',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 20, 13, 739242)),
        ),
        migrations.AlterField(
            model_name='chatbody',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 20, 13, 739242)),
        ),
    ]
