# Generated by Django 4.0.1 on 2022-02-02 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0003_chatbody_sender_alter_chat_date_alter_chatbody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 31, 25, 589851)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbody',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 31, 25, 589851)),
        ),
    ]
