# Generated by Django 4.0.1 on 2022-02-02 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chat_date_alter_chatbody_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 35, 47, 808653)),
        ),
        migrations.AlterField(
            model_name='chatbody',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 12, 35, 47, 808653)),
        ),
    ]
